### PR TITLE
Added pmm

### PR DESCRIPTION
**Pull request by genomez**

### CODE REVIEW

**Comment by angrycuban13** [comment]
Wouldn't this be better served as an alias? @austinwbest

**Comment by davidnewhall** [comment]
It should have its own icon. I'm going to test symlinks.

**Comment by austinwbest** [comment]
> Wouldn't this be better served as an alias? @austinwbest

Dockwatch will eventually have its own icon (just not an image person so it'll take a bit, took 3 years for me to get around to notifiarr lol)

**Comment by davidnewhall** [comment]
Go ahead and remove the dock watch png file. We can re-commit with a symlink.

**Pull request merged**
